# Generated by Django 5.0.6 on 2024-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSundry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('billSundryName', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoiceNumber', models.IntegerField()),
                ('customerName', models.CharField(max_length=30)),
                ('billingAddress', models.CharField(max_length=50)),
                ('shippingAddress', models.CharField(max_length=50)),
                ('GSTIN', models.CharField(max_length=30)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
